kind: Deployment
apiVersion: apps/v1
metadata:
  name: healthsecurityagency-frontend-deployment
  labels:
    app: healthsecurityagency-frontend
spec:
  selector:
    matchLabels:
      app: healthsecurityagency-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: healthsecurityagency-frontend
        version: v1
    spec:
      containers:
      - name: healthsecurityagency-frontend
        image: 'fra.ocir.io/frsxwtjslf35/demo/healthsecurityagency-frontend:latest'
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: https://i25fky4dpjckqerar545wea6tq.apigateway.eu-frankfurt-1.oci.customer-oci.com/healthsecurityagency-api
        - name: REACT_APP_MODE
          value: HEALTHSECURITYAGENCY
        - name: REACT_APP_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: obp-restproxy-token
              key: token
      imagePullSecrets:
      - name: ocirsecret
---
kind: Service
apiVersion: v1
metadata:
  name: healthsecurityagency-frontend-service
  labels:
    app: healthsecurityagency-frontend
spec:
  type: ClusterIP
  selector:
    app: healthsecurityagency-frontend
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthsecurityagency-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "health.blockchain.ivandelic.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: healthsecurityagency-frontend-service
            port:
              number: 3000