kind: Deployment
apiVersion: apps/v1
metadata:
  name: taxadministration-bc-frontend-deployment
  labels:
    app: taxadministration-bc-frontend
spec:
  selector:
    matchLabels:
      app: taxadministration-bc-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: taxadministration-bc-frontend
        version: v1
    spec:
      containers:
        - name: taxadministration-bc-frontend
          image: 'eu-frankfurt-1.ocir.io/oraseemeaceeociworkshop/ivandelic/taxadministration/taxadministration-frontend:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: https://i25fky4dpjckqerar545wea6tq.apigateway.eu-frankfurt-1.oci.customer-oci.com/taxadministration-bc-api
            - name: REACT_APP_MODE
              value: TAXADMINISTRATION
            - name: REACT_APP_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: obp-restproxy-token
                  key: token
      imagePullSecrets:
      - name: ocirsecret
---
kind: Service
apiVersion: v1
metadata:
  name: taxadministration-bc-frontend-service
spec:
  type: ClusterIP
  selector:
    app: taxadministration-bc-frontend
  ports:
  - port: 3000
    targetPort: 3000
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: taxadministration-bc-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: tls-secret
  rules:
  - host: "taxadministration.blockchain.ivandelic.com"
    http:
      paths:
      - backend:
          serviceName: taxadministration-bc-frontend-service
          servicePort: 3000
